import sys
import sysconfig
from pathlib import Path

import pytest

from acornfs.errors import AcornFSError
from acornfs.nautilus_install import (
    DESKTOP_FILE_NAME,
    MIME_PACKAGE_NAME,
    desktop_file_path,
    install_extension,
    mime_package_path,
    uninstall_extension,
)


def test_installs_and_removes_complete_desktop_integration(
    tmp_path: Path, monkeypatch: object
) -> None:
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path))  # type: ignore[attr-defined]
    target = install_extension()
    content = target.read_text(encoding="utf-8")
    assert target == tmp_path / "nautilus-python" / "extensions" / "nautilus_acornfs.py"
    assert repr(sys.executable) in content
    assert str(sysconfig.get_path("purelib")) in content
    assert "AcornFSMenuProvider" in content
    assert "AcornFSPropertiesModelProvider" in content
    mime_content = mime_package_path().read_text(encoding="utf-8")
    assert mime_package_path() == tmp_path / "mime" / "packages" / MIME_PACKAGE_NAME
    assert 'value="Hugo" offset="513"' in mime_content
    assert 'type="application/x-acorn-adfs"' in mime_content
    assert 'pattern="*.dsc"' in mime_content
    assert 'pattern="*.dat"' not in mime_content
    assert 'pattern="*.adf"' in mime_content
    assert 'pattern="*.ads"' in mime_content
    assert 'pattern="*.adm"' in mime_content
    assert 'pattern="*.adl"' in mime_content
    assert 'pattern="*.hdf"' in mime_content
    assert 'pattern="*.hd4"' in mime_content
    assert 'type="application/x-acorn-dfs"' in mime_content
    assert 'pattern="*.ssd"' in mime_content
    assert 'pattern="*.dsd"' in mime_content
    assert 'type="application/x-acorn-mmb"' in mime_content
    assert 'pattern="*.mmb"' in mime_content
    desktop_content = desktop_file_path().read_text(encoding="utf-8")
    assert desktop_file_path() == tmp_path / "applications" / DESKTOP_FILE_NAME
    assert "desktop-open %U" in desktop_content
    assert "x-scheme-handler/acornfs" in desktop_content
    assert "application/x-acorn-dfs" in desktop_content
    assert "application/x-acorn-mmb" in desktop_content
    assert "NoDisplay=true" in desktop_content
    assert uninstall_extension() == target
    assert not target.exists()
    assert not mime_package_path().exists()
    assert not desktop_file_path().exists()


def test_refuses_to_remove_foreign_extension(tmp_path: Path, monkeypatch: object) -> None:
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path))  # type: ignore[attr-defined]
    target = tmp_path / "nautilus-python" / "extensions" / "nautilus_acornfs.py"
    target.parent.mkdir(parents=True)
    target.write_text("# user file\n", encoding="utf-8")
    with pytest.raises(AcornFSError, match="Refusing"):
        uninstall_extension()


def test_install_removes_generated_legacy_bootstrap(tmp_path: Path, monkeypatch: object) -> None:
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path))  # type: ignore[attr-defined]
    legacy = tmp_path / "nautilus-python" / "extensions" / "acornfs.py"
    legacy.parent.mkdir(parents=True)
    legacy.write_text("# Generated by acornfs install-nautilus\n", encoding="utf-8")
    install_extension()
    assert not legacy.exists()
