"""Per-user installation of the Nautilus Python extension."""

from __future__ import annotations

import os
import pwd
import subprocess
import sys
import sysconfig
from pathlib import Path

from acornfs.errors import AcornFSError

MARKER = "# Generated by acornfs install-nautilus"


def extension_path() -> Path:
    configured = os.environ.get("XDG_DATA_HOME")
    if configured:
        data_home = Path(configured)
    else:
        account_home = Path(pwd.getpwuid(os.getuid()).pw_dir)
        data_home = account_home / ".local" / "share"
    return data_home / "nautilus-python" / "extensions" / "acornfs.py"


def install_extension(*, restart: bool = False) -> Path:
    target = extension_path()
    target.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
    source_root = Path(__file__).resolve().parents[1]
    dependency_root = Path(sysconfig.get_path("purelib"))
    content = (
        f"{MARKER}\n"
        "import sys\n"
        f"sys.path.insert(0, {str(dependency_root)!r})\n"
        f"sys.path.insert(0, {str(source_root)!r})\n"
        "from acornfs_nautilus import extension as _extension\n"
        f"_extension.configure_command([{sys.executable!r}, '-m', 'acornfs.cli'])\n"
        "AcornFSMenuProvider = _extension.AcornFSMenuProvider\n"
    )
    temporary = target.with_suffix(".py.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.chmod(0o644)
    temporary.replace(target)
    if restart:
        subprocess.run(["nautilus", "--quit"], check=False)
    return target


def uninstall_extension(*, restart: bool = False) -> Path:
    target = extension_path()
    if not target.exists():
        return target
    try:
        first_line = target.read_text(encoding="utf-8").splitlines()[0]
    except (OSError, IndexError) as exc:
        raise AcornFSError(f"Cannot verify installed extension {target}: {exc}") from exc
    if first_line != MARKER:
        raise AcornFSError(f"Refusing to remove an extension not created by AcornFS: {target}")
    target.unlink()
    if restart:
        subprocess.run(["nautilus", "--quit"], check=False)
    return target
