"""Per-user installation of the Nautilus Python extension."""

from __future__ import annotations

import os
import pwd
import shutil
import subprocess
import sys
import sysconfig
import uuid
from pathlib import Path

from acornfs.errors import AcornFSError

MARKER = "# Generated by acornfs install-nautilus"
XML_MARKER = "<!-- Generated by acornfs install-nautilus -->"
EXTENSION_NAME = "nautilus_acornfs.py"
LEGACY_EXTENSION_NAME = "acornfs.py"
MIME_PACKAGE_NAME = "acornfs.xml"
DESKTOP_FILE_NAME = "org.acornfs.NautilusAcornFS.desktop"


def data_home() -> Path:
    configured = os.environ.get("XDG_DATA_HOME")
    if configured:
        return Path(configured).expanduser()
    account_home = Path(pwd.getpwuid(os.getuid()).pw_dir)
    return account_home / ".local" / "share"


def extension_path() -> Path:
    return data_home() / "nautilus-python" / "extensions" / EXTENSION_NAME


def mime_package_path() -> Path:
    return data_home() / "mime" / "packages" / MIME_PACKAGE_NAME


def desktop_file_path() -> Path:
    return data_home() / "applications" / DESKTOP_FILE_NAME


def _generated_exists(target: Path, *, marker: str = MARKER) -> bool:
    if not target.exists():
        return False
    try:
        first_line = target.read_text(encoding="utf-8").splitlines()[0]
    except (OSError, UnicodeError, IndexError) as exc:
        raise AcornFSError(f"Cannot verify installed integration file {target}: {exc}") from exc
    if first_line != marker:
        raise AcornFSError(
            f"Refusing to modify an integration file not created by AcornFS: {target}"
        )
    return True


def _remove_if_generated(target: Path, *, marker: str = MARKER) -> bool:
    if not _generated_exists(target, marker=marker):
        return False
    target.unlink()
    return True


def _write_generated(target: Path, content: str, *, marker: str = MARKER) -> None:
    target.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
    _generated_exists(target, marker=marker)
    temporary = target.with_name(f".{target.name}.{uuid.uuid4().hex}.tmp")
    try:
        with temporary.open("x", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.chmod(0o644)
        temporary.replace(target)
    finally:
        temporary.unlink(missing_ok=True)


def _desktop_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`")
    escaped = escaped.replace("$", "\\$").replace("%", "%%")
    return f'"{escaped}"'


def mime_package_content() -> str:
    """Return the shared MIME package used by user and system installations."""

    return f"""{XML_MARKER}
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-acorn-adfs">
    <comment>Acorn ADFS disk image</comment>
    <magic priority="80">
      <match type="string" value="Hugo" offset="513"/>
    </magic>
    <glob pattern="*.adf" weight="60"/>
    <glob pattern="*.ads" weight="70"/>
    <glob pattern="*.adm" weight="70"/>
    <glob pattern="*.adl" weight="70"/>
    <glob pattern="*.hdf" weight="70"/>
    <glob pattern="*.HDF" weight="70"/>
    <glob pattern="*.hd4" weight="70"/>
    <glob pattern="*.HD4" weight="70"/>
  </mime-type>
  <mime-type type="application/x-beebscsi-descriptor">
    <comment>BeebSCSI geometry descriptor</comment>
    <glob pattern="*.dsc" weight="70"/>
    <glob pattern="*.DSC" weight="70"/>
  </mime-type>
  <mime-type type="application/x-acorn-dfs">
    <comment>Acorn DFS disk image</comment>
    <glob pattern="*.ssd" weight="70"/>
    <glob pattern="*.SSD" weight="70"/>
    <glob pattern="*.dsd" weight="70"/>
    <glob pattern="*.DSD" weight="70"/>
  </mime-type>
  <mime-type type="application/x-acorn-mmb">
    <comment>BBC Micro MMB disk container</comment>
    <glob pattern="*.mmb" weight="70"/>
    <glob pattern="*.MMB" weight="70"/>
  </mime-type>
</mime-info>
"""


def desktop_file_content(command: list[str] | None = None) -> str:
    """Return the desktop handler for an explicit, shell-free command."""

    selected = command or [sys.executable, "-m", "acornfs.cli"]
    executable = " ".join(_desktop_quote(part) for part in selected)
    return f"""{MARKER}
[Desktop Entry]
Type=Application
Name=AcornFS Image Mounter
Comment=Open a supported Acorn disk image read-only
Exec={executable} desktop-open %U
Icon=drive-harddisk
Terminal=false
NoDisplay=true
StartupNotify=true
MimeType=application/x-acorn-adfs;application/x-acorn-dfs;application/x-acorn-mmb;application/x-beebscsi-descriptor;x-scheme-handler/acornfs;
Categories=System;FileTools;
"""


def extension_loader_content(command: list[str], *, python_paths: tuple[Path, ...] = ()) -> str:
    """Return the Nautilus loader shared by user and Debian package layouts."""

    path_setup = "".join(f"sys.path.insert(0, {str(path)!r})\n" for path in python_paths)
    import_setup = "import sys\n" if python_paths else ""
    return (
        f"{MARKER}\n"
        f"{import_setup}"
        f"{path_setup}"
        "from acornfs_nautilus import extension as _extension\n"
        f"_extension.configure_command({command!r})\n"
        "class AcornFSMenuProvider(_extension.AcornFSMenuProvider):\n"
        "    pass\n"
        "class AcornFSPropertiesModelProvider(_extension.AcornFSPropertiesModelProvider):\n"
        "    pass\n"
    )


def _refresh_database(command: str, directory: Path) -> None:
    if not directory.exists():
        return
    executable = shutil.which(command)
    if executable is None:
        return
    result = subprocess.run(
        [executable, str(directory)],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        detail = result.stderr.strip() or f"{command} failed"
        raise AcornFSError(f"Could not refresh desktop integration: {detail}")


def install_extension(*, restart: bool = False) -> Path:
    """Install the Nautilus extension, MIME definitions and desktop handler."""

    target = extension_path()
    _remove_if_generated(target.parent / LEGACY_EXTENSION_NAME)
    source_root = Path(__file__).resolve().parents[1]
    dependency_root = Path(sysconfig.get_path("purelib"))
    content = extension_loader_content(
        [sys.executable, "-m", "acornfs.cli"],
        python_paths=(dependency_root, source_root),
    )
    _write_generated(target, content)
    _write_generated(mime_package_path(), mime_package_content(), marker=XML_MARKER)
    _write_generated(desktop_file_path(), desktop_file_content())
    _refresh_database("update-mime-database", data_home() / "mime")
    _refresh_database("update-desktop-database", data_home() / "applications")
    if restart:
        subprocess.run(["nautilus", "--quit"], check=False)
    return target


def uninstall_extension(*, restart: bool = False) -> Path:
    """Remove only integration files generated by AcornFS and refresh caches."""

    target = extension_path()
    _remove_if_generated(target)
    _remove_if_generated(target.parent / LEGACY_EXTENSION_NAME)
    _remove_if_generated(mime_package_path(), marker=XML_MARKER)
    _remove_if_generated(desktop_file_path())
    _refresh_database("update-mime-database", data_home() / "mime")
    _refresh_database("update-desktop-database", data_home() / "applications")
    if restart:
        subprocess.run(["nautilus", "--quit"], check=False)
    return target
